{
    "code":0,
    "msg":"",
    "count":1000,
    "data":[{
        "id": 10000,
        "username": "user-0",
        "department": "研发部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10001,
        "username": "user-1",
        "department": "设计部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10002,
        "username": "user-2",
        "department": "产品部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10003,
        "username": "user-3",
        "department": "设计部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10004,
        "username": "user-4",
        "department": "服务部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10005,
        "username": "user-5",
        "department": "品牌部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10006,
        "username": "user-6",
        "department": "产品部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10007,
        "username": "user-7",
        "department": "研发部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10008,
        "username": "user-8",
        "department": "设计部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10009,
        "username": "user-9",
        "department": "安全中心",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10010,
        "username": "user-10",
        "department": "品牌部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10011,
        "username": "user-11",
        "department": "售后部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10012,
        "username": "user-12",
        "department": "客服部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10013,
        "username": "user-13",
        "department": "研发部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10014,
        "username": "user-14",
        "department": "品牌部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10015,
        "username": "user-15",
        "department": "设计部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10016,
        "username": "user-16",
        "department": "研发部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10017,
        "username": "user-17",
        "department": "销售部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10018,
        "username": "user-18",
        "department": "市场部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10019,
        "username": "user-19",
        "department": "研发部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10020,
        "username": "user-20",
        "department": "安全部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10021,
        "username": "user-21",
        "department": "后勤部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10022,
        "username": "user-22",
        "department": "产品部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10023,
        "username": "user-23",
        "department": "设计部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10024,
        "username": "user-24",
        "department": "市场部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10025,
        "username": "user-25",
        "department": "客服部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10026,
        "username": "user-26",
        "department": "研发部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10027,
        "username": "user-27",
        "department": "销售部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }, {
        "id": 10028,
        "username": "user-28",
        "department": "设计部",
        "operation": "登录",
        "time": "2018-07-06",
        "remark": "登录"
    }, {
        "id": 10029,
        "username": "user-29",
        "department": "产品部",
        "operation": "退出",
        "time": "2018-07-06",
        "remark": "退出"
    }]
}