language: node_js

node_js: 0.10

before_script:
  - node --version
  - npm --version
  - npm install -g grunt-cli

  # Install meteor
  - curl https://install.meteor.com | /bin/sh
  # Install spacejam, Meteor's CI helper
  - npm install -g spacejam

script: grunt test --verbose
